import Anthropic from "@anthropic-ai/sdk";
import { loadKb } from "./kb";
import { getIndex } from "./retrieval";
import { buildSystemPrompt, PROMPT_VERSION } from "./system-prompt";
import { ACTIVE_TOOLS, TOOLS_VERSION } from "./tools";

/**
 * Agent core: retrieval-grounded turn against claude-haiku-4-5 (spec 01 §2;
 * model id verified via the claude-api skill at build time, 2026-08-02).
 *
 * MOCK_AGENT=1 (CI, previews) returns a deterministic reply so the whole
 * pipeline is testable without a key ever reaching CI.
 */

export const MODEL_ID = "claude-haiku-4-5";
export const MAX_TOKENS = 1024;

// Haiku 4.5 public pricing, USD per token (claude-api skill, 2026-08-02).
const INPUT_USD_PER_TOKEN = 1 / 1_000_000;
const OUTPUT_USD_PER_TOKEN = 5 / 1_000_000;
const CACHE_READ_USD_PER_TOKEN = 0.1 / 1_000_000;
const CACHE_WRITE_USD_PER_TOKEN = 1.25 / 1_000_000;

export interface AgentTurnInput {
  /** Prior turns, oldest first. */
  history: { role: "user" | "assistant"; content: string }[];
  /** The new user message. */
  message: string;
}

export interface AgentTurnResult {
  reply: string;
  /** Document titles cited by the model (parsed from its source line). */
  sources: string[];
  /** Document titles retrieval injected this turn (superset of sources). */
  retrieved: string[];
  usage: {
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens: number;
    cacheWriteTokens: number;
    costUsd: number;
  };
  promptVersion: string;
  toolsVersion: string;
  model: string;
  mocked: boolean;
}

export function isMockMode(): boolean {
  return process.env.MOCK_AGENT === "1" || !process.env.ANTHROPIC_API_KEY;
}

/** Parse and strip the trailing `[sources: A; B]` line the prompt mandates. */
export function extractSources(text: string): {
  reply: string;
  sources: string[];
} {
  const match = text.match(/\n?\[sources:\s*([^\]]+)\]\s*$/i);
  if (!match) return { reply: text.trim(), sources: [] };
  const sources = match[1]
    .split(";")
    .map((s) => s.trim())
    .filter(Boolean);
  return { reply: text.slice(0, match.index).trim(), sources };
}

function buildExcerpts(message: string): {
  excerpts: string;
  retrieved: string[];
} {
  const index = getIndex(loadKb());
  const chunks = index.search(message, 6);
  const retrieved = [...new Set(chunks.map((c) => c.docTitle))];
  const excerpts = chunks
    .map(
      (c) =>
        `<excerpt doc="${c.docTitle}" section="${c.section}">\n${c.text}\n</excerpt>`,
    )
    .join("\n");
  return { excerpts, retrieved };
}

let client: Anthropic | null = null;
function getClient(): Anthropic {
  if (!client) client = new Anthropic();
  return client;
}

export async function runAgentTurn(
  input: AgentTurnInput,
): Promise<AgentTurnResult> {
  const { excerpts, retrieved } = buildExcerpts(input.message);
  const base = {
    retrieved,
    promptVersion: PROMPT_VERSION,
    toolsVersion: TOOLS_VERSION,
    model: MODEL_ID,
  };

  if (isMockMode()) {
    const top = retrieved[0];
    const reply = top
      ? `(Demo mock) Here is what I found related to your question in our ${top} document. In production this answer is generated by ${MODEL_ID} from the same excerpts.`
      : "(Demo mock) I don't have information about that. Would you like me to connect you with our front desk?";
    return {
      ...base,
      reply,
      sources: top ? [top] : [],
      usage: {
        inputTokens: 0,
        outputTokens: 0,
        cacheReadTokens: 0,
        cacheWriteTokens: 0,
        costUsd: 0,
      },
      mocked: true,
    };
  }

  const response = await getClient().messages.create({
    model: MODEL_ID,
    max_tokens: MAX_TOKENS,
    system: buildSystemPrompt(excerpts),
    tools: ACTIVE_TOOLS.length ? ACTIVE_TOOLS : undefined,
    messages: [
      ...input.history.map((m) => ({ role: m.role, content: m.content })),
      { role: "user" as const, content: input.message },
    ],
  });

  const text = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("");
  const { reply, sources } = extractSources(text);

  const u = response.usage;
  const cacheRead = u.cache_read_input_tokens ?? 0;
  const cacheWrite = u.cache_creation_input_tokens ?? 0;
  const costUsd =
    u.input_tokens * INPUT_USD_PER_TOKEN +
    u.output_tokens * OUTPUT_USD_PER_TOKEN +
    cacheRead * CACHE_READ_USD_PER_TOKEN +
    cacheWrite * CACHE_WRITE_USD_PER_TOKEN;

  return {
    ...base,
    reply,
    sources,
    usage: {
      inputTokens: u.input_tokens,
      outputTokens: u.output_tokens,
      cacheReadTokens: cacheRead,
      cacheWriteTokens: cacheWrite,
      costUsd,
    },
    mocked: false,
  };
}
